export PATH="/usr/local/sbin:$PATH"

for file in ~/.{exports,aliases,iterm2,extra}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi
