export PATH="/usr/local/sbin:$PATH"

# Docker
export DOCKER_HOST=tcp://192.168.99.100:2376
export DOCKER_MACHINE_NAME=default
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=/Users/lakiboy/.docker/machine/machines/default
