export PATH="/usr/local/sbin:$PATH"
export PROMPT_COMMAND='if [ -d .git ]; then echo -e "\033[32m$(parse_git_branch)\033[00m"; fi'

parse_git_branch() {
    git branch | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

for file in ~/.{exports,aliases,iterm2,extra}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi
