
set nocompatible

set backspace=indent,eol,start

" Syntax highlighting
syntax on

" Enable file type detection and do language-dependent indenting
filetype plugin indent on

" Show line numbers
set number

" Allow hidden buffer
set hidden
