---

fish_user: "{{ ansible_facts['user_id'] }}"
fish_config_file: "{{ ansible_facts['user_dir'] }}/.config/fish/config.fish"
fish_exports:
  GPG_TTY: "(tty)"
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"

fish_fisher_enabled: true
fish_fisher_config_file: "{{ ansible_facts['user_dir'] }}/.config/fish/functions/fisher.fish"
fish_fisher_plugins:
  - "jorgebucaran/fisher"
  - "jorgebucaran/nvm.fish"
  - "reitzig/sdkman-for-fish@v2.1.0"
  - "gazorby/fish-abbreviation-tips"
