tap 'caskroom/cask'
tap 'caskroom/versions'

cask '1password'
cask 'alfred'
cask 'appcleaner'
cask 'atom'
cask 'ccmenu'
cask 'cyberduck'
cask 'dash'
cask 'diffmerge'
cask 'docker'
cask 'dropbox'
cask 'evernote'
cask 'google-chrome'
cask 'iterm2'
cask 'launchrocket'
cask 'ngrok'
cask 'phpstorm'
cask 'postico'
cask 'sequel-pro'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'synology-cloud-station-drive'
cask 'teamviewer'
cask 'telegram'
cask 'tunnelbear'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'vlc'
cask 'whatsapp'
cask 'xld'

# Java
cask 'java'
cask 'intellij-idea-ce'
cask 'jd-gui'

tap 'ethereum/ethereum'
tap 'homebrew/bundle'
tap 'homebrew/completions'
tap 'thoughtbot/formulae'
tap 'paritytech/paritytech'

brew 'ansible'
brew 'bash-completion'
brew 'bitcoin'
brew 'csvfix'
brew 'curl'
brew 'dnsmasq'
brew 'geth'
brew 'git'
brew 'git-flow'
brew 'go'
brew 'gnu-sed'
brew 'jsonpp'
brew 'mas'
brew 'parity'
brew 'pgcli'
brew 'pgloader'
brew 'rcm'
brew 's3cmd'
brew 'solidity'
brew 'ssh-copy-id'
brew 'vagrant-completion'
brew 'vim'

# Java
brew 'maven'
brew 'maven-completion'

mas 'CoinBar', id: 957162288
mas 'feedly', id: 865500966
mas 'Kindle', id: 405399194
mas 'Microsoft Remote Desktop', id: 715768417
mas 'MONIT', id: 1014850245
mas 'Monosnap', id: 540348655
mas 'Wunderlist', id: 410628904
