tap 'caskroom/cask'
tap 'caskroom/versions'

cask '1password'
cask 'alfred'
cask 'appcleaner'
cask 'atom'
cask 'ccmenu'
cask 'dash'
cask 'diffmerge'
cask 'docker-toolbox'
cask 'dropbox'
cask 'evernote'
cask 'google-chrome'
cask 'hipchat'
cask 'iterm2'
cask 'launchrocket'
cask 'ngrok'
cask 'phpstorm'
cask 'postico'
cask 'sequel-pro'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'synology-cloud-station-drive'
cask 'telegram'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'whatsapp'
# cask 'vlc'

tap 'homebrew/bundle'
tap 'homebrew/completions'
tap 'thoughtbot/formulae'

brew 'ansible'
brew 'bash-completion'
brew 'docker-machine-nfs'
brew 'dnsmasq'
brew 'git'
brew 'git-flow'
brew 'gnu-sed'
brew 'mas'
brew 'rcm'
brew 's3cmd'
brew 'ssh-copy-id'
brew 'vim'

mas 'Wunderlist', id: 410628904
mas 'Monosnap', id: 540348655
