---

git_user_name: Dmitrijs Lakacauskis
git_user_email: d@dmitrijs.io

github_token: ~

fish_exports:
  GPG_TTY: "(tty)"
  LANG: "en_US.UTF-8"
  PGHOST: 127.0.0.1
  PGUSER: admin
  PGPASSWORD: admin

colima_cpu: 4
colima_memory: 12
colima_disk: 64

homebrew_taps:
  - buo/cask-upgrade
  - hashicorp/tap
  - robscott/tap
  - teamookla/speedtest

homebrew_cask_apps:
  - 1password
  - alfred
  - appcleaner
  - arc
  - cyberduck
  - dropbox
  - firefox
  - github
  - google-chrome
  - google-cloud-sdk
  - gpg-suite
  - istat-menus
  - jetbrains-toolbox
  - karabiner-elements
  - lens
  - logi-options-plus
  - microsoft-teams
  - obsidian
  - nordvpn
  - ngrok
  - poedit
  - protonvpn
  - proxyman
  - raspberry-pi-imager
  - spotify
  - vanilla
  - visual-studio-code
  - vlc
  - zoom

homebrew_installed_packages:
  - ansible
  - ansible-lint
  - awscli
  - caddy
  - circleci
  - cmctl
  - colima
  - curl
  - dockerize
  - ffmpeg
  - fish
  - hcloud
  - helm
  - ghostty
  - jq
  - hashicorp/tap/waypoint
  - hashicorp/tap/terraform
  - htop
  - httpie
  - git
  - gnu-sed
  - k9s
  - kdoctor
  - kubectx
  - kustomize
  - make
  - mas
  - orbstack
  - podman
  - pgcli
  - pyenv-virtualenv
  - rbenv
  - robscott/tap/kube-capacity
  - shellcheck
  - skaffold
  - speedtest
  - ssh-copy-id
  - stern
  - terminal-notifier
  - wget

mas_installed_apps:
  - { id: 640199958, name: "Developer" }
  - { id: 425264550, name: "Blackmagic Disk Speed Test" }
  - { id: 406056744, name: "Evernote" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" }
  - { id: 1274495053, name: "Microsoft To Do" }
  - { id: 540348655, name: "Monosnap" }
  - { id: 1289583905, name: "Pixelmator Pro" }
  - { id: 803453959, name: "Slack" }
  - { id: 1545870783, name: "Color Picker" }
  - { id: 747648890, name: "Telegram" }
  - { id: 310633997, name: "WhatsApp" }
  - { id: 497799835, name: "Xcode" }
