---

git_user_name: Dmitrijs Lakacauskis
git_user_email: d@dmitrijs.io

# https://github.com/settings/tokens
github_token: ~

fish_exports:
  GPG_TTY: "(tty)"
  LANG: "en_US.UTF-8"

  PGHOST: 127.0.0.1
  PGUSER: admin
  PGPASSWORD: admin

  RABBITMQ_ENDPOINT: http://127.0.0.1:15672
  RABBITMQ_USERNAME: admin
  RABBITMQ_PASSWORD: admin

homebrew_taps:
  - buo/cask-upgrade
  - hashicorp/tap
  - kubewall/tap
  - robscott/tap
  - shivammathur/php
  - teamookla/speedtest

homebrew_cask_apps:
  - 1password
  - alfred
  - android-studio
  - arc
  - bruno
  - chatgpt
  - claude
  - claude-code
  - clipbook
  - cyberduck
  - dropbox
  - firefox
  - gcloud-cli
  - ghostty
  - google-chrome
  - istat-menus
  - jetbrains-toolbox
  - jiggler
  - karabiner-elements
  - logi-options+
  - ngrok
  - obsidian
  - orbstack
  - pearcleaner
  - poedit
  - proxyman
  - raspberry-pi-imager
  - shottr
  - slack
  - transmission
  - vanilla
  - visual-studio-code
  - vlc
  - wifiman
  - zoom

homebrew_installed_packages:
  - awscli
  - caddy
  - circleci
  - cmctl
  - curl
  - ffmpeg
  - fish
  - gh
  - git
  - gnu-sed
  - gnupg
  - graphviz
  - hashicorp/tap/terraform
  - hcloud
  - helm
  - helmfile
  - hermes-agent
  - htop
  - httpie
  - iperf3
  - jq
  - k9s
  - kubectx
  - kubernetes-cli
  - kustomize
  - make
  - mas
  - pgcli
  - pinentry-mac
  - podman
  - pyenv
  - pyenv-virtualenv
  - rbenv
  - ripgrep
  - robscott/tap/kube-capacity
  - shellcheck
  - skaffold
  - speedtest
  - ssh-copy-id
  - stern
  - terragrunt
  - uv
  - wget

mas_installed_apps:
  - { id: 425264550, name: "Blackmagic Disk Speed Test" }
  - { id: 1545870783, name: "Color Picker" }
  - { id: 640199958, name: "Developer" }
  - { id: 409183694, name: "Keynote" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" }
  - { id: 1274495053, name: "Microsoft To Do" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }
  - { id: 1289583905, name: "Pixelmator Pro" }
  - { id: 747648890, name: "Telegram" }
  - { id: 899247664, name: "TestFlight" }
  - { id: 310633997, name: "WhatsApp" }
  - { id: 497799835, name: "Xcode" }
