---

git_user_name: Dmitrijs Lakacauskis
git_user_email: d@dmitrijs.io

github_token: ~

fish_exports:
  GPG_TTY: "(tty)"
  LANG: "en_US.UTF-8"
  PGHOST: 127.0.0.1
  PGUSER: admin
  PGPASSWORD: admin

colima_cpu: 4
colima_memory: 12
colima_disk: 64

homebrew_taps:
  - buo/cask-upgrade
  - hashicorp/tap
  - homebrew/services
  - teamookla/speedtest

homebrew_cask_apps:
  - 1password
  - alfred
  - appcleaner
  - arc
  - cyberduck
  - diffmerge
  - dropbox
  - firefox
  - github
  - google-chrome
  - google-cloud-sdk
  - gpg-suite
  - iterm2
  - istat-menus
  - jetbrains-toolbox
  - karabiner-elements
  - logi-options-plus
  - microsoft-teams
  - obsidian
  - nordvpn
  - ngrok
  - poedit
  - proxyman
  - raspberry-pi-imager
  - spotify
  - visual-studio-code
  - vlc
  - zoom

homebrew_installed_packages:
  - ansible
  - ansible-lint
  - awscli
  - caddy
  - circleci
  - colima
  - curl
  - docker
  - docker-compose
  - docker-credential-helper
  - dockerize
  - fish
  - jq
  - hashicorp/tap/waypoint
  - hashicorp/tap/terraform
  - htop
  - httpie
  - git
  - gnu-sed
  - make
  - mas
  - orbstack
  - postgresql@15
  - shellcheck
  - speedtest
  - ssh-copy-id
  - terraform
  - terminal-notifier
  - tilt
  - wget

mas_installed_apps:
  - { id: 640199958, name: "Apple Developer" }
  - { id: 406056744, name: "Evernote" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" }
  - { id: 1274495053, name: "Microsoft To Do" }
  - { id: 540348655, name: "Monosnap" }
  - { id: 1289583905, name: "Pixelmator Pro" }
  - { id: 803453959, name: "Slack for Desktop" }
  - { id: 1508732804, name: "Soulver 3" }
  - { id: 747648890, name: "Telegram" }
  - { id: 310633997, name: "WhatsApp Messenger" }
  - { id: 497799835, name: "Xcode" }
