---

git_user_name: Dmitrijs Lakacauskis
git_user_email: d@dmitrijs.io

github_token: ~

fish_exports:
  GPG_TTY: "(tty)"
  LANG: "en_US.UTF-8"
  PGHOST: 127.0.0.1
  PGUSER: admin
  PGPASSWORD: admin

colima_cpu: 4
colima_memory: 12
colima_disk: 64

homebrew_taps:
  - buo/cask-upgrade
  - hashicorp/tap
  - robscott/tap
  - teamookla/speedtest

homebrew_cask_apps:
  - 1password
  - alfred
  - appcleaner
  - arc
  - cyberduck
  - diffmerge
  - dropbox
  - firefox
  - github
  - google-chrome
  - google-cloud-sdk
  - gpg-suite
  - iterm2
  - istat-menus
  - jetbrains-toolbox
  - karabiner-elements
  - lens
  - logi-options-plus
  - microsoft-teams
  - obsidian
  - nordvpn
  - ngrok
  - poedit
  - proxyman
  - raspberry-pi-imager
  - rocket
  - spotify
  - vanilla
  - visual-studio-code
  - vlc
  - zoom

homebrew_installed_packages:
  - ansible
  - ansible-lint
  - awscli
  - caddy
  - circleci
  - colima
  - curl
  - dockerize
  - fish
  - hcloud
  - helm
  - ghostty
  - jq
  - hashicorp/tap/waypoint
  - hashicorp/tap/terraform
  - htop
  - httpie
  - git
  - gnu-sed
  - k9s
  - kubectx
  - kustomize
  - make
  - mas
  - orbstack
  - podman
  - pgcli
  - robscott/tap/kube-capacity
  - shellcheck
  - skaffold
  - speedtest
  - ssh-copy-id
  - terminal-notifier
  - wget

mas_installed_app_ids:
  - 640199958   # Apple Developer
  - 425264550   # Blackmagic Disk Speed Test
  - 406056744   # Evernote
  - 1295203466  # Microsoft Remote Desktop
  - 1274495053  # Microsoft To Do
  - 540348655   # Monosnap
  - 1289583905  # Pixelmator Pro
  - 803453959   # Slack for Desktop
  - 1508732804  # Soulver 3
  - 1545870783  # System Color Picker
  - 747648890   # Telegram
  - 310633997   # WhatsApp Messenger
  - 497799835   # Xcode
