---

- name: Dotfiles | Copy exports
  template: "src=exports.j2 dest={{ playbook_dir }}/dotfiles/exports owner={{ devenv_user }} mode=0755"

- name: Dotfiles | Copy gitconfig
  template: "src=gitconfig.j2 dest={{ playbook_dir }}/dotfiles/gitconfig owner={{ devenv_user }} mode=0644"
