
- name: Services | DNS | Copy dnsmasq.conf
  template: "src=dnsmasq.conf.j2 dest=/usr/local/etc/dnsmasq.conf owner={{ devenv_user }} mode=0644"

- name: Services | DNS | Create resolver directory
  file: dest=/etc/resolver state=directory
  become: yes
  become_method: sudo

# If fails, see: https://github.com/ansible/ansible/issues/13763
- name: Services | DNS | Configure resolver
  copy: "src=resolver.conf dest=/etc/resolver/{{ item.domain }}"
  become: yes
  become_method: sudo
  with_items: '{{ devenv_dnsmasq_hosts }}'
