---

- name: Packages | Install docker-sync
  gem: name=docker-sync user_install=no
  become: yes

- name: Packages | Install terraforming
  gem: name=terraforming

- name: Packages | Install Ansible Lint
  pip: name=ansible-lint executable=pip3

- name: Packages | Install dgoss
  get_url:
    url: '{{ item.url }}'
    dest: '/usr/local/bin/{{ item.binary }}'
    mode: 0755
  with_items:
    - { url: 'https://github.com/aelsabbahy/goss/releases/download/{{ devenv_goss_version }}/goss-linux-amd64', binary: goss }
    - { url: 'https://github.com/aelsabbahy/goss/releases/download/{{ devenv_goss_version }}/dgoss', binary: dgoss }

- name: Packages | Link gettext tools
  homebrew:
    name: gettext
    state: linked
    install_options: force
  changed_when: false
