---

- name: Dnsmasq | Copy dnsmasq.conf
  template: src=dnsmasq.conf dest=/usr/local/etc/dnsmasq.conf owner='{{ devenv_user }}' mode=0644

- name: Dnsmasq | Ensure resolver directory exists
  file: dest=/etc/resolver state=directory
  become: yes

- name: Dnsmasq | Configure resolver
  copy: src=resolver.conf dest='/etc/resolver/{{ item.domain }}'
  with_items: '{{ devenv_dnsmasq_hosts }}'
  become: yes
