---

- name: Manage Docker runtime.
  hosts: local

  vars_files:
    - ../default.config.yml

  pre_tasks:
    - name: Include custom configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - role: colima
      tags: [docker]
