---

- name: Configure basic OSX software.
  hosts: local

  vars:
    git_user_name: Dmitrijs Lakacauskis
    git_user_email: d@dmitrijs.io

  roles:
    - role: dotfiles
      tags: [dotfiles]

    - role: fish
      tags: [fish]

    - role: git
      tags: [git]
