---

- name: Install software.
  hosts: local

  vars_files:
    - ../default.config.yml

  pre_tasks:
    - name: Include custom configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: [homebrew]
    - role: geerlingguy.mac.mas
      tags: [mas]
